%%% 说明
%###################################################
% 简易计算器 1.0
% 作者：张泽寰
% 时间：2015/12/15
% small_2009@yeah.net
%###################################################
%%% --------------------figureStart--------------------
% 可以用Ctrl + R注释本段
%CleanCheck=input('建议在启动本计算器前清空内存变量，这意味着您的变量区将会被重置，请确认？（Y/N）','s');
%if(strcmp(CleanCheck,'Y')||strcmp(CleanCheck,'y'))
%    clear;
%else
%    if(strcmp(CleanCheck,'N')||strcmp(CleanCheck,'n'))
%        clear CleanCheck
%    else
%        error('输入错误')
%    end
%end
CleanCheck='Y';
%%% --------------------objectClass-------------------
object.screensize=get(0,'ScreenSize');
CALC.width=300;
CALC.high=420;
object.button_1.width=55.5;
object.button_1.high=40;
CALC.PositionStyle='center'; %Offer three style: center left right

%%% --------------------figureLoad--------------------
switch(CALC.PositionStyle)
    case 'center'
        CALC.left=(object.screensize(3)-CALC.width)/2;
        CALC.top=(object.screensize(4)-CALC.high)/2;
    case 'left'
        CALC.left=0;
        CALC.top=(object.screensize(4)-CALC.high)/2;
    case 'right'
        CALC.left=object.screensize(3)-CALC.width;
        CALC.top=(object.screensize(4)-CALC.high)/2;
    otherwise
        if(isempty(CALC.left)&&isempty(CALC.top))
            error('No Position Input');
        end
end
CALC.num=[];
CALC.ans=[];
CALC.EQ=0;
CALC.mark=1;
CALC.outList=cell(1,1000);
%%% --------------------figureDraw--------------------
CALC.main=figure('numbertitle','off','name',['简易计算器'],'menubar',...
    'none','position',[CALC.left CALC.top CALC.width CALC.high],'resize','off');
%%%%--------------------------------------------------
%%%添加背景----------------------------
movegui(CALC.main,'center');
axes('visible','off','units','normalized','position',[0,0,1,1]);
cData=imread('picture.jpg');
image(cData);
axis off;
set(CALC.main,'visible','on');
global aa;
global bb;
%===================================================
CALC.text1=uicontrol('style','edit','backgroundcolor',[1,1,1],'position',...
    [4,CALC.high-90,CALC.width-5,85],'tag','myedit','fontsize',10,'string','',...
    'horizontalalignment','left','style','list');
%%%---------------------------------------------------------------------
%%%---------------------------------------------------------------------
CALC.button1=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4,CALC.high-...
    object.button_1.high-90-4,object.button_1.width,object.button_1.high],...
    'string','7','callback','CALC.num=[CALC.num ''7''];set(CALC.text1,''string'',CALC.num);');
CALC.button2=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width,CALC.high-...
    object.button_1.high-90-4,object.button_1.width,object.button_1.high],...
    'string','8','callback','CALC.num=[CALC.num ''8''];set(CALC.text1,''string'',CALC.num);');
CALC.button3=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high-90-4,object.button_1.width,object.button_1.high],...
    'string','9','callback','CALC.num=[CALC.num ''9''];set(CALC.text1,''string'',CALC.num);');
%-------------------------------------------------------------------------------
CALC.button4=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high-90-4,object.button_1.width,object.button_1.high],...
    'string','DEL','callback','CALC.num(end)=[];set(CALC.text1,''string'',CALC.num);');
CALC.button5=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high-90-4,object.button_1.width,object.button_1.high],...
    'string','AC','callback','CALC.num=[];set(CALC.text1,''string'',CALC.num);');
%%%--------------------------------------------------------------------------
CALC.button6=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*1,CALC.high-...
    object.button_1.high*2-90-4*2,object.button_1.width,object.button_1.high],...
    'string','4','callback','CALC.num=[CALC.num ''4''];set(CALC.text1,''string'',CALC.num);');
CALC.button7=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width,CALC.high-...
    object.button_1.high*2-90-4*2,object.button_1.width,object.button_1.high],...
    'string','5','callback','CALC.num=[CALC.num ''5''];set(CALC.text1,''string'',CALC.num);');
CALC.button8=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high*2-90-4*2,object.button_1.width,object.button_1.high],...
    'string','6','callback','CALC.num=[CALC.num ''6''];set(CALC.text1,''string'',CALC.num);');
CALC.button9=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high*2-90-4*2,object.button_1.width,object.button_1.high],...
    'string','×','callback','CALC.num=[CALC.num ''*''];set(CALC.text1,''string'',CALC.num);');
CALC.button10=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high*2-90-4*2,object.button_1.width,object.button_1.high],...
    'string','÷','callback','CALC.num=[CALC.num ''/''];set(CALC.text1,''string'',CALC.num);');
CALC.button11=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*1,CALC.high-...
    object.button_1.high*3-90-4*3,object.button_1.width,object.button_1.high],...
    'string','1','callback','CALC.num=[CALC.num ''1''];set(CALC.text1,''string'',CALC.num);');
CALC.button12=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width,CALC.high-...
    object.button_1.high*3-90-4*3,object.button_1.width,object.button_1.high],...
    'string','2','callback','CALC.num=[CALC.num ''2''];set(CALC.text1,''string'',CALC.num);');
CALC.button13=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high*3-90-4*3,object.button_1.width,object.button_1.high],...
    'string','3','callback','CALC.num=[CALC.num ''3''];set(CALC.text1,''string'',CALC.num);');
CALC.button14=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high*3-90-4*3,object.button_1.width,object.button_1.high],...
    'string','+','callback','CALC.num=[CALC.num ''+''];set(CALC.text1,''string'',CALC.num);');
CALC.button15=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high*3-90-4*3,object.button_1.width,object.button_1.high],...
    'string','-','callback','CALC.num=[CALC.num ''-''];set(CALC.text1,''string'',CALC.num);');
CALC.button16=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4,CALC.high-...
    object.button_1.high*4-90-4*4,object.button_1.width,object.button_1.high],...
    'string','0','callback','CALC.num=[CALC.num ''0''];set(CALC.text1,''string'',CALC.num);');
CALC.button17=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width*1,CALC.high-...
    object.button_1.high*4-90-4*4,object.button_1.width,object.button_1.high],...
    'string','.','callback','CALC.num=[CALC.num ''.''];set(CALC.text1,''string'',CALC.num);');
CALC.button18=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high*4-90-4*4,object.button_1.width,object.button_1.high],...
    'string','EXP','callback','CALC.num=[CALC.num ''e''];set(CALC.text1,''string'',CALC.num);');
CALC.button19=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high*4-90-4*4,object.button_1.width,object.button_1.high],...
    'string','ans','callback','if(CALC.EQ==1),CALC.num=[CALC.num num2str(CALC.ans)];else,CALC.num=CALC.num;end;set(CALC.text1,''string'',CALC.num);');
%%%--------------------------------------------------------------------------------------------------
%%%--------------------------------------------------------------------------------------------------
CALC.button20=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high*4-90-4*4,object.button_1.width,object.button_1.high],...
    'string','=','callback',...
    ['Tmp=CALC.num;CALC.num=eval(CALC.num);CALC.outList{1}=Tmp;CALC.ans=CALC.num;' ...
    'CALC.EQ=1;CALC.outList{2}=[''ans='' num2str(CALC.num)];CALC.mark=CALC.mark+2;' ...
    'set(CALC.text1,''string'',CALC.outList);CALC.num=[];clear Tmp;CALC.outList(3:CALC.mark+2)=CALC.outList(1:CALC.mark);']);
%%%--------------------------------------------------------------------------------------------------
%%%--------------------------------------------------------------------------------------------------
CALC.button21=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4,CALC.high-...
    object.button_1.high*5-105-4*5,object.button_1.width,object.button_1.high],...
    'string','^','callback','CALC.num=[CALC.num ''^''];set(CALC.text1,''string'',CALC.num);');
CALC.button22=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width*1,CALC.high-...
    object.button_1.high*5-105-4*5,object.button_1.width,object.button_1.high],...
    'string','(','callback','CALC.num=[CALC.num ''(''];set(CALC.text1,''string'',CALC.num);');
CALC.button23=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high*5-105-4*5,object.button_1.width,object.button_1.high],...
    'string',')','callback','CALC.num=[CALC.num '')''];set(CALC.text1,''string'',CALC.num);');
CALC.button24=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high*5-105-4*5,object.button_1.width,object.button_1.high],...
    'string','^2','callback','CALC.num=[CALC.num ''^2''];set(CALC.text1,''string'',CALC.num);');
CALC.button24=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high*5-105-4*5,object.button_1.width,object.button_1.high],...
    'string','π','callback','CALC.num=[CALC.num ''pi''];set(CALC.text1,''string'',CALC.num);');
CALC.button21=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4,CALC.high-...
    object.button_1.high*6-105-4*6,object.button_1.width,object.button_1.high],...
    'string','log(','callback','CALC.num=[CALC.num ''log(''];set(CALC.text1,''string'',CALC.num);');
CALC.button22=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width*1,CALC.high-...
    object.button_1.high*6-105-4*6,object.button_1.width,object.button_1.high],...
    'string','ln(','callback','CALC.num=[CALC.num ''ln(''];set(CALC.text1,''string'',CALC.num);');
CALC.button23=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high*6-105-4*6,object.button_1.width,object.button_1.high],...
    'string','factorial(','callback','CALC.num=[CALC.num ''factorial(''];set(CALC.text1,''string'',CALC.num);');
CALC.button24=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high*6-105-4*6,object.button_1.width,object.button_1.high],...
    'string','Pol(','callback','CALC.num=[CALC.num ''Pol(''];set(CALC.text1,''string'',CALC.num);');
CALC.button24=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high*6-105-4*6,object.button_1.width,object.button_1.high],...
    'string',',','callback','CALC.num=[CALC.num '',''];set(CALC.text1,''string'',CALC.num);');
CALC.button21=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4,CALC.high-...
    object.button_1.high*7-105-4*7,object.button_1.width,object.button_1.high],...
    'string','tan(','callback','CALC.num=[CALC.num ''tan(''];set(CALC.text1,''string'',CALC.num);');
CALC.button22=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*2+object.button_1.width*1,CALC.high-...
    object.button_1.high*7-105-4*7,object.button_1.width,object.button_1.high],...
    'string','sin(','callback','CALC.num=[CALC.num ''sin(''];set(CALC.text1,''string'',CALC.num);');
CALC.button23=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*3+object.button_1.width*2,CALC.high-...
    object.button_1.high*7-105-4*7,object.button_1.width,object.button_1.high],...
    'string','cos(','callback','CALC.num=[CALC.num ''cos(''];set(CALC.text1,''string'',CALC.num);');
CALC.button24=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*4+object.button_1.width*3,CALC.high-...
    object.button_1.high*7-105-4*7,object.button_1.width,object.button_1.high],...
    'string','sqrt(','callback','CALC.num=[CALC.num ''sqrt(''];set(CALC.text1,''string'',CALC.num);');
CALC.button24=uicontrol('style','pushbutton','backgroundcolor','w','ForegroundColor',bb,'fontweight','bold','position',[4*5+object.button_1.width*4,CALC.high-...
    object.button_1.high*7-105-4*7,object.button_1.width,object.button_1.high],...
    'string','exp(','callback','CALC.num=[CALC.num ''exp(''];set(CALC.text1,''string'',CALC.num);');